# Generated by Django 3.0.11 on 2021-01-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('P', 'Player'), ('S', 'Superuser')], default='P', max_length=1, verbose_name='Role of the user'),
        ),
    ]
