# Generated by Django 3.2.6 on 2021-09-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210905_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
