# Generated by Django 3.2.9 on 2021-11-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_player_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user_type',
            field=models.CharField(default='Player', editable=False, max_length=6),
        ),
    ]
