# Generated by Django 3.2.9 on 2021-11-30 01:35

from django.db import migrations, models
import user_auth.models.profiles


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_player_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.FileField(default='member-default.jpg', upload_to=user_auth.models.profiles.UploadImage, verbose_name='foto'),
        ),
    ]
