# Generated by Django 4.1.3 on 2022-11-08 19:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('question', models.CharField(max_length=200)),
                (
                    'level',
                    models.CharField(
                        choices=[
                            ('Fácil', 'Easy'),
                            ('Moderado', 'Moderate'),
                            ('Difícil', 'Hard'),
                            ('Muito Difícil', 'Very Hard'),
                        ],
                        default='Moderado',
                        max_length=16,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                (
                    'quiz',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='questions',
                        to='quizzes.quiz',
                    ),
                ),
            ],
        ),
    ]
