# Generated by Django 3.2.6 on 2021-09-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210906_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[(1, 'Primeira Resposta'), (2, 'Segunda Resposta'), (3, 'Terceira Resposta')], max_length=1, verbose_name='Resposta Correta'),
        ),
    ]
