# Generated by Django 3.2.6 on 2021-09-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('1', 'Primeira Resposta'), ('2', 'Segunda Resposta'), ('3', 'Terceira Resposta')], max_length=1, verbose_name='Resposta Correta'),
        ),
    ]
