# Generated by Django 3.2.9 on 2021-11-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questao', '0001_initial'),
        ('resposta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questao.questao'),
        ),
    ]
