# Generated by Django 3.1.5 on 2021-01-28 13:42

from django.db import migrations, models
import django.db.models.deletion
import quiz_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_classificacao', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=100, unique=True)),
                ('resposta', models.IntegerField(validators=[quiz_api.models.Pergunta.validate_resposta])),
                ('opcao1', models.CharField(max_length=100)),
                ('opcao2', models.CharField(max_length=100)),
                ('opcao3', models.CharField(max_length=100)),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.classificacao')),
            ],
        ),
    ]
