# Generated by Django 3.2.7 on 2021-09-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_quiz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, to='api.Question'),
        ),
    ]
