# Generated by Django 3.2.7 on 2021-09-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_quiz_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='question',
            new_name='questions',
        ),
    ]
