# Generated by Django 3.2.7 on 2021-09-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_quiz_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
