# Generated by Django 3.2.9 on 2021-11-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20211128_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='enunciation',
            field=models.CharField(max_length=128),
        ),
    ]
