# Generated by Django 4.2.2 on 2023-07-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.ManyToManyField(to='quiz.question', verbose_name='questions'),
        ),
    ]
