# Generated by Django 4.2.2 on 2023-07-12 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_quiz_quiz_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.ManyToManyField(blank=True, to='quiz.question', verbose_name='questions'),
        ),
    ]
