# Generated by Django 3.2.9 on 2021-11-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20211128_1424'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('is_correct', 'question')},
        ),
    ]
