# Generated by Django 3.1 on 2021-03-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210325_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_A',
            field=models.CharField(max_length=200, verbose_name='Letra A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_B',
            field=models.CharField(max_length=200, verbose_name='Letra B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_C',
            field=models.CharField(max_length=200, verbose_name='Letra C'),
        ),
    ]
