# Generated by Django 3.1.6 on 2021-02-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210216_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answers',
            field=models.ManyToManyField(blank=True, to='quiz.Answer'),
        ),
    ]
