# Generated by Django 3.1.6 on 2021-02-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
