# Generated by Django 3.1 on 2021-03-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210325_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.category'),
        ),
    ]
