# Generated by Django 3.2.9 on 2021-11-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_playerrank_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerrank',
            name='points',
        ),
        migrations.AddField(
            model_name='playerrank',
            name='points',
            field=models.ManyToManyField(to='quiz.Point'),
        ),
    ]
