# Generated by Django 3.2.9 on 2021-11-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20211129_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrank',
            name='total_points',
            field=models.FloatField(default=0),
        ),
    ]
