# Generated by Django 3.2.9 on 2021-11-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_playerrank_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerrank',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
