# Generated by Django 3.2.16 on 2023-01-06 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_text', models.CharField(max_length=100, verbose_name='Tipo da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200, verbose_name='Texto da Pergunta')),
                ('first_choice', models.CharField(max_length=100, verbose_name='Primeira Escolha')),
                ('second_choice', models.CharField(max_length=100, verbose_name='Segunda Escolha')),
                ('third_choice', models.CharField(max_length=100, verbose_name='Terceira Escolha')),
                ('correct_choice', models.CharField(choices=[('first_choice', 'Primeira escolha'), ('second_choice', 'Segunda escolha'), ('third_choice', 'Terceira escolha')], max_length=100, verbose_name='Escolha correta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anwser', to='quizzes.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ('id',),
            },
        ),
    ]
