# Generated by Django 3.0.11 on 2021-01-25 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterField(
            model_name='categoryscore',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='Question ctegories'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryscore',
            unique_together={('profile', 'category')},
        ),
    ]
