# Generated by Django 3.1.4 on 2021-01-05 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequential', models.IntegerField(blank=True, default=1)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('questao_wrong', models.ManyToManyField(blank=True, related_name='question_erradas', to='quiz.Question')),
                ('question_correct', models.ManyToManyField(blank=True, related_name='question_correct', to='quiz.Question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
