# Generated by Django 3.1.4 on 2021-01-07 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='questao_wrong',
            new_name='question_wrong',
        ),
    ]
