# Generated by Django 3.1.4 on 2021-01-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210107_0049'),
        ('user', '0002_auto_20210107_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='question_wrong',
            field=models.ManyToManyField(blank=True, related_name='question_wrong', to='quiz.Question'),
        ),
    ]
