# Generated by Django 3.1.4 on 2021-01-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210107_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
