# Generated by Django 3.1.4 on 2021-01-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
