# Generated by Django 3.2 on 2021-10-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='content',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='questions',
            field=models.ManyToManyField(to='quiz.Question'),
        ),
    ]
