# Generated by Django 3.2 on 2021-10-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20211010_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
