# Generated by Django 3.2.6 on 2021-09-05 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(null=True, verbose_name='Pontuação')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.category', verbose_name='Categoria')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Rank',
                'db_table': 'rank',
            },
        ),
    ]
