# Generated by Django 3.1.5 on 2021-01-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='question',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
