# Generated by Django 3.1.5 on 2021-01-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210108_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='name',
        ),
        migrations.AddField(
            model_name='match',
            name='answers_one',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='answers_three',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='answers_two',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='correct_option',
            field=models.CharField(choices=[('1', 'Answers One'), ('2', 'Answers Two'), ('3', 'Answers Three')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='player_response',
            field=models.CharField(choices=[('1', 'Answers One'), ('2', 'Answers Two'), ('3', 'Answers Three')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
