# Generated by Django 4.1.3 on 2022-11-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='categories',
            field=models.ManyToManyField(
                related_name='accounts', to='quizzes.category'
            ),
        ),
    ]
