# Generated by Django 3.1.4 on 2021-12-06 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20211206_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=django.utils.timezone.now),
            preserve_default=django.utils.timezone.now,
        ),
    ]
