# Generated by Django 3.1.4 on 2021-12-06 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20211206_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['-score', 'created_at']},
        ),
    ]
