# Generated by Django 3.1.4 on 2021-01-05 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=700, verbose_name='Question')),
                ('option_a', models.CharField(max_length=500, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Option B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Option C')),
                ('correct', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
    ]
