# Generated by Django 3.1.4 on 2021-01-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
