# Generated by Django 3.1.4 on 2021-01-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210107_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_user',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2, null=True),
        ),
    ]
