# Generated by Django 3.1.4 on 2020-12-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_quizpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpage',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.answer'),
            preserve_default=False,
        ),
    ]
