# Generated by Django 3.1.4 on 2020-12-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_quizpage_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizpage',
            old_name='answer',
            new_name='answers',
        ),
    ]
