# Generated by Django 3.1.4 on 2020-12-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20201206_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizpage',
            name='answers',
        ),
    ]
