# Generated by Django 3.1.4 on 2020-12-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20201206_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizpage',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.question'),
        ),
    ]
