# Generated by Django 3.1.4 on 2020-12-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20201207_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='vote',
        ),
        migrations.AddField(
            model_name='quizpage',
            name='vote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
