# Generated by Django 3.1.4 on 2020-12-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20201207_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizpage',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
