# Generated by Django 4.1.3 on 2022-11-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("desciption", models.CharField(max_length=255)),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="Quizzes", to="questions.question"
                    ),
                ),
            ],
        ),
    ]
