# Generated by Django 4.1.3 on 2022-11-09 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="desciption",
            new_name="description",
        ),
    ]
