# Generated by Django 3.1.5 on 2021-01-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_submitplayer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitPlayer',
        ),
    ]
