# Generated by Django 3.1.5 on 2021-01-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
