# Generated by Django 3.1 on 2021-03-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210329_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='global_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
